/**
 * Portal API
 * RC Portal
 *
 * OpenAPI spec version: v1
 * Contact: ifx@fas.harvard.edu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.PortalApi) {
      root.PortalApi = {};
    }
    root.PortalApi.Build = factory(root.PortalApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The Build model module.
   * @module model/Build
   * @version v1
   */

  /**
   * Constructs a new <code>Build</code>.
   * @alias module:model/Build
   * @class
   * @param name {String} 
   * @param app {String} 
   * @param version {String} 
   * @param details {String} 
   * @param buildStack {String} 
   * @param requestor {String} 
   * @param deploymentTooling {String} 
   * @param activation {String} 
   */
  var exports = function(name, app, version, details, buildStack, requestor, deploymentTooling, activation) {
    var _this = this;

    _this['name'] = name;
    _this['app'] = app;
    _this['version'] = version;
    _this['details'] = details;
    _this['build_stack'] = buildStack;
    _this['requestor'] = requestor;


    _this['deployment_tooling'] = deploymentTooling;
    _this['activation'] = activation;

  };

  /**
   * Constructs a <code>Build</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Build} obj Optional instance to populate.
   * @return {module:model/Build} The populated <code>Build</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('app')) {
        obj['app'] = ApiClient.convertToType(data['app'], 'String');
      }
      if (data.hasOwnProperty('version')) {
        obj['version'] = ApiClient.convertToType(data['version'], 'String');
      }
      if (data.hasOwnProperty('details')) {
        obj['details'] = ApiClient.convertToType(data['details'], 'String');
      }
      if (data.hasOwnProperty('build_stack')) {
        obj['build_stack'] = ApiClient.convertToType(data['build_stack'], 'String');
      }
      if (data.hasOwnProperty('requestor')) {
        obj['requestor'] = ApiClient.convertToType(data['requestor'], 'String');
      }
      if (data.hasOwnProperty('publication')) {
        obj['publication'] = ApiClient.convertToType(data['publication'], 'String');
      }
      if (data.hasOwnProperty('request_ref')) {
        obj['request_ref'] = ApiClient.convertToType(data['request_ref'], 'String');
      }
      if (data.hasOwnProperty('deployment_tooling')) {
        obj['deployment_tooling'] = ApiClient.convertToType(data['deployment_tooling'], 'String');
      }
      if (data.hasOwnProperty('activation')) {
        obj['activation'] = ApiClient.convertToType(data['activation'], 'String');
      }
      if (data.hasOwnProperty('comments')) {
        obj['comments'] = ApiClient.convertToType(data['comments'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * @member {String} app
   */
  exports.prototype['app'] = undefined;
  /**
   * @member {String} version
   */
  exports.prototype['version'] = undefined;
  /**
   * @member {String} details
   */
  exports.prototype['details'] = undefined;
  /**
   * @member {String} build_stack
   */
  exports.prototype['build_stack'] = undefined;
  /**
   * @member {String} requestor
   */
  exports.prototype['requestor'] = undefined;
  /**
   * @member {String} publication
   */
  exports.prototype['publication'] = undefined;
  /**
   * @member {String} request_ref
   */
  exports.prototype['request_ref'] = undefined;
  /**
   * @member {String} deployment_tooling
   */
  exports.prototype['deployment_tooling'] = undefined;
  /**
   * @member {String} activation
   */
  exports.prototype['activation'] = undefined;
  /**
   * @member {String} comments
   */
  exports.prototype['comments'] = undefined;



  return exports;
}));


