/**
 * Portal API
 * RC Portal
 *
 * OpenAPI spec version: v1
 * Contact: ifx@fas.harvard.edu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/GetBasicsByLogin'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/GetBasicsByLogin'));
  } else {
    // Browser globals (root is window)
    if (!root.PortalApi) {
      root.PortalApi = {};
    }
    root.PortalApi.GetBasicsByLoginApi = factory(root.PortalApi.ApiClient, root.PortalApi.GetBasicsByLogin);
  }
}(this, function(ApiClient, GetBasicsByLogin) {
  'use strict';

  /**
   * GetBasicsByLogin service.
   * @module api/GetBasicsByLoginApi
   * @version v1
   */

  /**
   * Constructs a new GetBasicsByLoginApi. 
   * @alias module:api/GetBasicsByLoginApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;



    /**
     * Return basic information (user full name, pi name, department, email ) given all or part of a login
     * @param {Object} opts Optional parameters
     * @param {String} opts.login 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:model/GetBasicsByLogin>} and HTTP response
     */
    this.getBasicsByLoginListWithHttpInfo = function(opts) {
      opts = opts || {};
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
        'login': opts['login'],
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['token'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = [GetBasicsByLogin];

      return this.apiClient.callApi(
        '/get-basics-by-login/', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Return basic information (user full name, pi name, department, email ) given all or part of a login
     * @param {Object} opts Optional parameters
     * @param {String} opts.login 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:model/GetBasicsByLogin>}
     */
    this.getBasicsByLoginList = function(opts) {
      return this.getBasicsByLoginListWithHttpInfo(opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }
  };

  return exports;
}));
