/**
 * Portal API
 * RC Portal
 *
 * OpenAPI spec version: v1
 * Contact: ifx@fas.harvard.edu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/GetUserList'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/GetUserList'));
  } else {
    // Browser globals (root is window)
    if (!root.PortalApi) {
      root.PortalApi = {};
    }
    root.PortalApi.GetUserListApi = factory(root.PortalApi.ApiClient, root.PortalApi.GetUserList);
  }
}(this, function(ApiClient, GetUserList) {
  'use strict';

  /**
   * GetUserList service.
   * @module api/GetUserListApi
   * @version v1
   */

  /**
   * Constructs a new GetUserListApi. 
   * @alias module:api/GetUserListApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;



    /**
     * Return basic information (user full name, pi name, department, email ) given a search term.   Logins are in a list.
     * @param {Object} opts Optional parameters
     * @param {String} opts.search 
     * @param {Number} opts.offset 
     * @param {Number} opts.limit 
     * @param {String} opts.orderBy 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:model/GetUserList>} and HTTP response
     */
    this.getUserListListWithHttpInfo = function(opts) {
      opts = opts || {};
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
        'search': opts['search'],
        'offset': opts['offset'],
        'limit': opts['limit'],
        'order_by': opts['orderBy'],
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['token'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = [GetUserList];

      return this.apiClient.callApi(
        '/get-user-list/', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Return basic information (user full name, pi name, department, email ) given a search term.   Logins are in a list.
     * @param {Object} opts Optional parameters
     * @param {String} opts.search 
     * @param {Number} opts.offset 
     * @param {Number} opts.limit 
     * @param {String} opts.orderBy 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:model/GetUserList>}
     */
    this.getUserListList = function(opts) {
      return this.getUserListListWithHttpInfo(opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }
  };

  return exports;
}));
