/**
 * Portal API
 * RC Portal
 *
 * OpenAPI spec version: v1
 * Contact: ifx@fas.harvard.edu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/OfficeHoursSignIn'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/OfficeHoursSignIn'));
  } else {
    // Browser globals (root is window)
    if (!root.PortalApi) {
      root.PortalApi = {};
    }
    root.PortalApi.OfficeHoursSignInsApi = factory(root.PortalApi.ApiClient, root.PortalApi.OfficeHoursSignIn);
  }
}(this, function(ApiClient, OfficeHoursSignIn) {
  'use strict';

  /**
   * OfficeHoursSignIns service.
   * @module api/OfficeHoursSignInsApi
   * @version v1
   */

  /**
   * Constructs a new OfficeHoursSignInsApi. 
   * @alias module:api/OfficeHoursSignInsApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;



    /**
     * ViewSet for OfficeHoursSignIn
     * @param {module:model/OfficeHoursSignIn} data 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/OfficeHoursSignIn} and HTTP response
     */
    this.officeHoursSignInsCreateWithHttpInfo = function(data) {
      var postBody = data;

      // verify the required parameter 'data' is set
      if (data === undefined || data === null) {
        throw new Error("Missing the required parameter 'data' when calling officeHoursSignInsCreate");
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['token'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = OfficeHoursSignIn;

      return this.apiClient.callApi(
        '/office-hours-sign-ins/', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * ViewSet for OfficeHoursSignIn
     * @param {module:model/OfficeHoursSignIn} data 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/OfficeHoursSignIn}
     */
    this.officeHoursSignInsCreate = function(data) {
      return this.officeHoursSignInsCreateWithHttpInfo(data)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * ViewSet for OfficeHoursSignIn
     * @param {Number} id A unique integer value identifying this office hours sign in.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    this.officeHoursSignInsDeleteWithHttpInfo = function(id) {
      var postBody = null;

      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling officeHoursSignInsDelete");
      }


      var pathParams = {
        'id': id
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['token'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = null;

      return this.apiClient.callApi(
        '/office-hours-sign-ins/{id}/', 'DELETE',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * ViewSet for OfficeHoursSignIn
     * @param {Number} id A unique integer value identifying this office hours sign in.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    this.officeHoursSignInsDelete = function(id) {
      return this.officeHoursSignInsDeleteWithHttpInfo(id)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * ViewSet for OfficeHoursSignIn
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:model/OfficeHoursSignIn>} and HTTP response
     */
    this.officeHoursSignInsListWithHttpInfo = function() {
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['token'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = [OfficeHoursSignIn];

      return this.apiClient.callApi(
        '/office-hours-sign-ins/', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * ViewSet for OfficeHoursSignIn
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:model/OfficeHoursSignIn>}
     */
    this.officeHoursSignInsList = function() {
      return this.officeHoursSignInsListWithHttpInfo()
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * ViewSet for OfficeHoursSignIn
     * @param {Number} id A unique integer value identifying this office hours sign in.
     * @param {module:model/OfficeHoursSignIn} data 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/OfficeHoursSignIn} and HTTP response
     */
    this.officeHoursSignInsPartialUpdateWithHttpInfo = function(id, data) {
      var postBody = data;

      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling officeHoursSignInsPartialUpdate");
      }

      // verify the required parameter 'data' is set
      if (data === undefined || data === null) {
        throw new Error("Missing the required parameter 'data' when calling officeHoursSignInsPartialUpdate");
      }


      var pathParams = {
        'id': id
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['token'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = OfficeHoursSignIn;

      return this.apiClient.callApi(
        '/office-hours-sign-ins/{id}/', 'PATCH',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * ViewSet for OfficeHoursSignIn
     * @param {Number} id A unique integer value identifying this office hours sign in.
     * @param {module:model/OfficeHoursSignIn} data 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/OfficeHoursSignIn}
     */
    this.officeHoursSignInsPartialUpdate = function(id, data) {
      return this.officeHoursSignInsPartialUpdateWithHttpInfo(id, data)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * ViewSet for OfficeHoursSignIn
     * @param {Number} id A unique integer value identifying this office hours sign in.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/OfficeHoursSignIn} and HTTP response
     */
    this.officeHoursSignInsReadWithHttpInfo = function(id) {
      var postBody = null;

      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling officeHoursSignInsRead");
      }


      var pathParams = {
        'id': id
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['token'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = OfficeHoursSignIn;

      return this.apiClient.callApi(
        '/office-hours-sign-ins/{id}/', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * ViewSet for OfficeHoursSignIn
     * @param {Number} id A unique integer value identifying this office hours sign in.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/OfficeHoursSignIn}
     */
    this.officeHoursSignInsRead = function(id) {
      return this.officeHoursSignInsReadWithHttpInfo(id)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * ViewSet for OfficeHoursSignIn
     * @param {Number} id A unique integer value identifying this office hours sign in.
     * @param {module:model/OfficeHoursSignIn} data 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/OfficeHoursSignIn} and HTTP response
     */
    this.officeHoursSignInsUpdateWithHttpInfo = function(id, data) {
      var postBody = data;

      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling officeHoursSignInsUpdate");
      }

      // verify the required parameter 'data' is set
      if (data === undefined || data === null) {
        throw new Error("Missing the required parameter 'data' when calling officeHoursSignInsUpdate");
      }


      var pathParams = {
        'id': id
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['token'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = OfficeHoursSignIn;

      return this.apiClient.callApi(
        '/office-hours-sign-ins/{id}/', 'PUT',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * ViewSet for OfficeHoursSignIn
     * @param {Number} id A unique integer value identifying this office hours sign in.
     * @param {module:model/OfficeHoursSignIn} data 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/OfficeHoursSignIn}
     */
    this.officeHoursSignInsUpdate = function(id, data) {
      return this.officeHoursSignInsUpdateWithHttpInfo(id, data)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }
  };

  return exports;
}));
