/**
 * Portal API
 * RC Portal
 *
 * OpenAPI spec version: v1
 * Contact: ifx@fas.harvard.edu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.PortalApi);
  }
}(this, function(expect, PortalApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new PortalApi.BuildReports();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('BuildReports', function() {
    it('should create an instance of BuildReports', function() {
      // uncomment below and update the code to test BuildReports
      //var instance = new PortalApi.BuildReports();
      //expect(instance).to.be.a(PortalApi.BuildReports);
    });

    it('should have the property appName (base name: "app_name")', function() {
      // uncomment below and update the code to test the property appName
      //var instance = new PortalApi.BuildReports();
      //expect(instance).to.be();
    });

    it('should have the property buildStackName (base name: "build_stack_name")', function() {
      // uncomment below and update the code to test the property buildStackName
      //var instance = new PortalApi.BuildReports();
      //expect(instance).to.be();
    });

    it('should have the property buildName (base name: "build_name")', function() {
      // uncomment below and update the code to test the property buildName
      //var instance = new PortalApi.BuildReports();
      //expect(instance).to.be();
    });

    it('should have the property buildOrder (base name: "build_order")', function() {
      // uncomment below and update the code to test the property buildOrder
      //var instance = new PortalApi.BuildReports();
      //expect(instance).to.be();
    });

    it('should have the property reportText (base name: "report_text")', function() {
      // uncomment below and update the code to test the property reportText
      //var instance = new PortalApi.BuildReports();
      //expect(instance).to.be();
    });

    it('should have the property deploymentToooling (base name: "deployment_toooling")', function() {
      // uncomment below and update the code to test the property deploymentToooling
      //var instance = new PortalApi.BuildReports();
      //expect(instance).to.be();
    });

  });

}));
