/**
 * p3 client
 * RC Portal
 *
 * OpenAPI spec version: v1
 * Contact: ifx@fas.harvard.edu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/App', 'model/AppTag', 'model/Build', 'model/BuildStack', 'model/OfficeHoursSignIn', 'api/AppTagsApi', 'api/AppsApi', 'api/BuildStacksApi', 'api/BuildsApi', 'api/GetBasicsByLoginApi', 'api/GetOrgNamesApi', 'api/GetPiNamesApi', 'api/OfficeHoursSignInsApi'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('./ApiClient'), require('./model/App'), require('./model/AppTag'), require('./model/Build'), require('./model/BuildStack'), require('./model/OfficeHoursSignIn'), require('./api/AppTagsApi'), require('./api/AppsApi'), require('./api/BuildStacksApi'), require('./api/BuildsApi'), require('./api/GetBasicsByLoginApi'), require('./api/GetOrgNamesApi'), require('./api/GetPiNamesApi'), require('./api/OfficeHoursSignInsApi'));
  }
}(function(ApiClient, App, AppTag, Build, BuildStack, OfficeHoursSignIn, AppTagsApi, AppsApi, BuildStacksApi, BuildsApi, GetBasicsByLoginApi, GetOrgNamesApi, GetPiNamesApi, OfficeHoursSignInsApi) {
  'use strict';

  /**
   * RC_Portal.<br>
   * The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
   * <p>
   * An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
   * <pre>
   * var P3Client = require('index'); // See note below*.
   * var xxxSvc = new P3Client.XxxApi(); // Allocate the API class we're going to use.
   * var yyyModel = new P3Client.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
   * and put the application logic within the callback function.</em>
   * </p>
   * <p>
   * A non-AMD browser application (discouraged) might do something like this:
   * <pre>
   * var xxxSvc = new P3Client.XxxApi(); // Allocate the API class we're going to use.
   * var yyy = new P3Client.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * </p>
   * @module index
   * @version v1
   */
  var exports = {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient: ApiClient,
    /**
     * The App model constructor.
     * @property {module:model/App}
     */
    App: App,
    /**
     * The AppTag model constructor.
     * @property {module:model/AppTag}
     */
    AppTag: AppTag,
    /**
     * The Build model constructor.
     * @property {module:model/Build}
     */
    Build: Build,
    /**
     * The BuildStack model constructor.
     * @property {module:model/BuildStack}
     */
    BuildStack: BuildStack,
    /**
     * The OfficeHoursSignIn model constructor.
     * @property {module:model/OfficeHoursSignIn}
     */
    OfficeHoursSignIn: OfficeHoursSignIn,
    /**
     * The AppTagsApi service constructor.
     * @property {module:api/AppTagsApi}
     */
    AppTagsApi: AppTagsApi,
    /**
     * The AppsApi service constructor.
     * @property {module:api/AppsApi}
     */
    AppsApi: AppsApi,
    /**
     * The BuildStacksApi service constructor.
     * @property {module:api/BuildStacksApi}
     */
    BuildStacksApi: BuildStacksApi,
    /**
     * The BuildsApi service constructor.
     * @property {module:api/BuildsApi}
     */
    BuildsApi: BuildsApi,
    /**
     * The GetBasicsByLoginApi service constructor.
     * @property {module:api/GetBasicsByLoginApi}
     */
    GetBasicsByLoginApi: GetBasicsByLoginApi,
    /**
     * The GetOrgNamesApi service constructor.
     * @property {module:api/GetOrgNamesApi}
     */
    GetOrgNamesApi: GetOrgNamesApi,
    /**
     * The GetPiNamesApi service constructor.
     * @property {module:api/GetPiNamesApi}
     */
    GetPiNamesApi: GetPiNamesApi,
    /**
     * The OfficeHoursSignInsApi service constructor.
     * @property {module:api/OfficeHoursSignInsApi}
     */
    OfficeHoursSignInsApi: OfficeHoursSignInsApi
  };

  return exports;
}));
