/**
 * p3 client
 * RC Portal
 *
 * OpenAPI spec version: v1
 * Contact: ifx@fas.harvard.edu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.P3Client);
  }
}(this, function(expect, P3Client) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new P3Client.AppTagsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('AppTagsApi', function() {
    describe('appTagsCreate', function() {
      it('should call appTagsCreate successfully', function(done) {
        //uncomment below and update the code to test appTagsCreate
        //instance.appTagsCreate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('appTagsDelete', function() {
      it('should call appTagsDelete successfully', function(done) {
        //uncomment below and update the code to test appTagsDelete
        //instance.appTagsDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('appTagsList', function() {
      it('should call appTagsList successfully', function(done) {
        //uncomment below and update the code to test appTagsList
        //instance.appTagsList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('appTagsPartialUpdate', function() {
      it('should call appTagsPartialUpdate successfully', function(done) {
        //uncomment below and update the code to test appTagsPartialUpdate
        //instance.appTagsPartialUpdate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('appTagsRead', function() {
      it('should call appTagsRead successfully', function(done) {
        //uncomment below and update the code to test appTagsRead
        //instance.appTagsRead(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('appTagsUpdate', function() {
      it('should call appTagsUpdate successfully', function(done) {
        //uncomment below and update the code to test appTagsUpdate
        //instance.appTagsUpdate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
