/**
 * p3 client
 * RC Portal
 *
 * OpenAPI spec version: v1
 * Contact: ifx@fas.harvard.edu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.P3Client);
  }
}(this, function(expect, P3Client) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new P3Client.BuildStacksApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('BuildStacksApi', function() {
    describe('buildStacksCreate', function() {
      it('should call buildStacksCreate successfully', function(done) {
        //uncomment below and update the code to test buildStacksCreate
        //instance.buildStacksCreate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('buildStacksDelete', function() {
      it('should call buildStacksDelete successfully', function(done) {
        //uncomment below and update the code to test buildStacksDelete
        //instance.buildStacksDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('buildStacksList', function() {
      it('should call buildStacksList successfully', function(done) {
        //uncomment below and update the code to test buildStacksList
        //instance.buildStacksList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('buildStacksPartialUpdate', function() {
      it('should call buildStacksPartialUpdate successfully', function(done) {
        //uncomment below and update the code to test buildStacksPartialUpdate
        //instance.buildStacksPartialUpdate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('buildStacksRead', function() {
      it('should call buildStacksRead successfully', function(done) {
        //uncomment below and update the code to test buildStacksRead
        //instance.buildStacksRead(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('buildStacksUpdate', function() {
      it('should call buildStacksUpdate successfully', function(done) {
        //uncomment below and update the code to test buildStacksUpdate
        //instance.buildStacksUpdate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
