/**
 * p3 client
 * RC Portal
 *
 * OpenAPI spec version: v1
 * Contact: ifx@fas.harvard.edu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.P3Client);
  }
}(this, function(expect, P3Client) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new P3Client.OfficeHoursSignInsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('OfficeHoursSignInsApi', function() {
    describe('officeHoursSignInsCreate', function() {
      it('should call officeHoursSignInsCreate successfully', function(done) {
        //uncomment below and update the code to test officeHoursSignInsCreate
        //instance.officeHoursSignInsCreate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('officeHoursSignInsDelete', function() {
      it('should call officeHoursSignInsDelete successfully', function(done) {
        //uncomment below and update the code to test officeHoursSignInsDelete
        //instance.officeHoursSignInsDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('officeHoursSignInsList', function() {
      it('should call officeHoursSignInsList successfully', function(done) {
        //uncomment below and update the code to test officeHoursSignInsList
        //instance.officeHoursSignInsList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('officeHoursSignInsPartialUpdate', function() {
      it('should call officeHoursSignInsPartialUpdate successfully', function(done) {
        //uncomment below and update the code to test officeHoursSignInsPartialUpdate
        //instance.officeHoursSignInsPartialUpdate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('officeHoursSignInsRead', function() {
      it('should call officeHoursSignInsRead successfully', function(done) {
        //uncomment below and update the code to test officeHoursSignInsRead
        //instance.officeHoursSignInsRead(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('officeHoursSignInsUpdate', function() {
      it('should call officeHoursSignInsUpdate successfully', function(done) {
        //uncomment below and update the code to test officeHoursSignInsUpdate
        //instance.officeHoursSignInsUpdate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
